spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_diary
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      #create, update
      ddl-auto: update
    show_sql: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  config:
    import:
      optional:
        - classpath:openai.properties



server:
  port: 8080

logging:
  level:
    org:
      springframework:
        security: DEBUG

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000